### ISSUE TITLE
"Unknown Channel" when editing voice-channel-game-list

### ISSUE THREAD

**Issue by YetAnotherGerrit** [YetAnotherGerrit/Ronja.js#41]
Error when editing the message:

```
DiscordAPIError[10003]: Unknown Channel
    at SequentialHandler.runRequest (/root/github/Ronja.js/node_modules/@discordjs/rest/dist/index.js:933:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (/root/github/Ronja.js/node_modules/@discordjs/rest/dist/index.js:712:14)
    at async REST.request (/root/github/Ronja.js/node_modules/@discordjs/rest/dist/index.js:1321:22)
    at async MessageManager.edit (/root/github/Ronja.js/node_modules/discord.js/src/managers/MessageManager.js:176:15) {
  rawError: { message: 'Unknown Channel', code: 10003 },
  code: 10003,
  status: 404,
  method: 'PATCH',
  url: 'xxx',
  requestBody: {
    files: [],
    json: {
      content: 'Diese Spiele werden von den Kanalmitgliedern gespielt:\n' +
```

**Comment by YetAnotherGerrit** [comment]
Same root cause and same fix as #44 — this was the same `myMsg.edit(...)` call in `updateChannelVoiceStatus` (`Zocken.js`), which has had `.catch(console.error)` attached since commit ac97408 ("Improve error handling", 2023-11-02) and still does today, so this error is caught and logged rather than surfacing. Closing as resolved.
