### ISSUE TITLE
Improve error handling: ZockenVoiceChannel "ChannelNotCached"

### ISSUE THREAD

**Issue by YetAnotherGerrit** [YetAnotherGerrit/Ronja.js#44]
```shell
/root/Ronja.js/node_modules/discord.js/src/structures/Message.js:723
    if (!this.channel) return Promise.reject(new DiscordjsError(ErrorCodes.ChannelNotCached));
                                             ^
Error [ChannelNotCached]: Could not find the channel where this message came from in the cache!
    at Message.edit (/root/Ronja.js/node_modules/discord.js/src/structures/Message.js:723:46)
    at Object.updateChannelVoiceStatus (/root/Ronja.js/ronja_modules/Zocken.js:362:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ChannelNotCached'
}
```

**Comment by YetAnotherGerrit** [comment]
This exact crash can no longer happen: `updateChannelVoiceStatus`'s `myMsg.edit(...)` call in `Zocken.js` has had `.catch(console.error)` attached since commit ac97408 ("Improve error handling", 2023-11-02), and it's still present today. The error now gets logged instead of crashing the process. Closing as resolved.
